name: beta-bridge-api-ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  deps-installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 21.7.1
      - run: npm install -g pnpm
      - run: pnpm install
     
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 21.7.1]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run build
